### ISSUE TITLE
Add-on failed to load

### ISSUE THREAD

**Issue by michaelcward1996** [Ajatt-Tools/learn-now-button#1]
This occurred even with all other addons disabled. 

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Korean Support⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 211, in loadAddons
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1336389630\__init__.py", line 26, in <module>
    from . import edit
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1336389630\edit.py", line 12, in <module>
    from .edit_behavior import updateFields
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1336389630\edit_behavior.py", line 11, in <module>
    from .edit_functions import (
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1336389630\edit_functions.py", line 15, in <module>
    from . import tts
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1336389630\tts.py", line 16, in <module>
    from .lib.gtts.tts import gTTS
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1336389630\lib\gtts\__init__.py", line 3, in <module>
    from .tts import gTTS, gTTSError
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1336389630\lib\gtts\tts.py", line 4, in <module>
    from .lang import tts_langs, _fallback_deprecated_lang
  File "C:\Users\micha\AppData\Roaming\Anki2\addons21\1336389630\lib\gtts\lang.py", line 2, in <module>
    from gtts.langs import _main_langs
ModuleNotFoundError: No module named 'gtts'

**Comment by tatsumoto-ren** [comment]
> When loading '⁨Korean Support⁩':

Based on the error it seems like [Korean Support](https://ankiweb.net/shared/info/1336389630) might be involved. People report similar problems in the review section of that add-on.
